# MySQL Database Information
host: "localhost"
port: 3306
database: ""
username: ""
password: ""

# Symbol
clan_currency_symbol: $

# Clan Settings
clan_creation_enabled: true
clan_creation_cost: 0.0
